// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/avaliacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/avaliacao">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/avaliacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/boletim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/boletim">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/boletim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/calendario/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendario">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/calendario/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/configuracoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracoes">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/configuracoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/cursos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cursos">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/cursos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/frequencia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/frequencia">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/frequencia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/horario/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/horario">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/horario/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/links/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/links">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/links/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/relatorio-avaliacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/relatorio-avaliacao">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/relatorio-avaliacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/turmas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/turmas">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/turmas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/usuarios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/usuarios">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/usuarios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/widgets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/widgets">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/widgets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/db-size/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/db-size">> = Specific
  const handler = {} as typeof import("../../app/api/admin/db-size/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/migrations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/migrations">> = Specific
  const handler = {} as typeof import("../../app/api/admin/migrations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/smtp-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/smtp-status">> = Specific
  const handler = {} as typeof import("../../app/api/admin/smtp-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/change-password">> = Specific
  const handler = {} as typeof import("../../app/api/auth/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/heartbeat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/heartbeat">> = Specific
  const handler = {} as typeof import("../../app/api/auth/heartbeat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/send-access-code/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/send-access-code">> = Specific
  const handler = {} as typeof import("../../app/api/auth/send-access-code/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/send-class-access-codes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/send-class-access-codes">> = Specific
  const handler = {} as typeof import("../../app/api/auth/send-class-access-codes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/student-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/student-login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/student-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/sync">> = Specific
  const handler = {} as typeof import("../../app/api/auth/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/links/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/links">> = Specific
  const handler = {} as typeof import("../../app/api/links/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/suggestions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/suggestions">> = Specific
  const handler = {} as typeof import("../../app/api/suggestions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/cursos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/cursos/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/v1/cursos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/cursos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/cursos">> = Specific
  const handler = {} as typeof import("../../app/api/v1/cursos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/notas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/notas">> = Specific
  const handler = {} as typeof import("../../app/api/v1/notas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/pensamento-dia/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/pensamento-dia">> = Specific
  const handler = {} as typeof import("../../app/api/v1/pensamento-dia/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/widgets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/widgets">> = Specific
  const handler = {} as typeof import("../../app/api/widgets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
